//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: [TEXT REMOVED by com.google.code.maven-replacer-plugin]
//


package de.tu_chemnitz.mi.barcd.xml.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtractionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtractionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="frame-number" type="{http://www.tu-chemnitz.de/informatik/mi/barcd}uint"/>
 *         &lt;element name="barcodes" type="{http://www.tu-chemnitz.de/informatik/mi/barcd}BarcodesType"/>
 *         &lt;element name="regions" type="{http://www.tu-chemnitz.de/informatik/mi/barcd}RegionsType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtractionType", propOrder = {

})
public class ExtractionElement {

    @XmlElement(name = "frame-number")
    protected int frameNumber;
    @XmlElement(required = true)
    protected BarcodesElement barcodes;
    @XmlElement(required = true)
    protected RegionsElement regions;

    /**
     * Gets the value of the frameNumber property.
     * 
     */
    public int getFrameNumber() {
        return frameNumber;
    }

    /**
     * Sets the value of the frameNumber property.
     * 
     */
    public void setFrameNumber(int value) {
        this.frameNumber = value;
    }

    /**
     * Gets the value of the barcodes property.
     * 
     * @return
     *     possible object is
     *     {@link BarcodesElement }
     *     
     */
    public BarcodesElement getBarcodes() {
        return barcodes;
    }

    /**
     * Sets the value of the barcodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BarcodesElement }
     *     
     */
    public void setBarcodes(BarcodesElement value) {
        this.barcodes = value;
    }

    /**
     * Gets the value of the regions property.
     * 
     * @return
     *     possible object is
     *     {@link RegionsElement }
     *     
     */
    public RegionsElement getRegions() {
        return regions;
    }

    /**
     * Sets the value of the regions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegionsElement }
     *     
     */
    public void setRegions(RegionsElement value) {
        this.regions = value;
    }

}
