//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: [TEXT REMOVED by com.google.code.maven-replacer-plugin]
//


package de.tu_chemnitz.mi.barcd.xml.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JobType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JobType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="source" type="{http://www.tu-chemnitz.de/informatik/mi/barcd}SourceChoiceType"/>
 *         &lt;element name="next-frame-number" type="{http://www.tu-chemnitz.de/informatik/mi/barcd}uint" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JobType", propOrder = {

})
public class JobElement {

    @XmlElement(required = true)
    protected SourceChoiceElement source;
    @XmlElement(name = "next-frame-number", defaultValue = "0")
    protected Integer nextFrameNumber;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link SourceChoiceElement }
     *     
     */
    public SourceChoiceElement getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceChoiceElement }
     *     
     */
    public void setSource(SourceChoiceElement value) {
        this.source = value;
    }

    /**
     * Gets the value of the nextFrameNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNextFrameNumber() {
        return nextFrameNumber;
    }

    /**
     * Sets the value of the nextFrameNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNextFrameNumber(Integer value) {
        this.nextFrameNumber = value;
    }

}
