//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.10 at 09:13:08 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tu-chemnitz.de/informatik/mi/barcd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.tu_chemnitz.mi.barcd.xml.binding;
