//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: [TEXT REMOVED by com.google.code.maven-replacer-plugin]
//


package de.tu_chemnitz.mi.barcd.xml.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SeekableSourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SeekableSourceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.tu-chemnitz.de/informatik/mi/barcd}SourceType">
 *       &lt;attribute name="initial-frame-number" type="{http://www.tu-chemnitz.de/informatik/mi/barcd}uint" default="0" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SeekableSourceType")
@XmlSeeAlso({
    ImageSequenceSourceElement.class,
    VideoStreamSourceElement.class,
    ImageCollectionSourceElement.class
})
public class SeekableSourceElement
    extends SourceElement
{

    @XmlAttribute(name = "initial-frame-number")
    protected Integer initialFrameNumber;

    /**
     * Gets the value of the initialFrameNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getInitialFrameNumber() {
        if (initialFrameNumber == null) {
            return  0;
        } else {
            return initialFrameNumber;
        }
    }

    /**
     * Sets the value of the initialFrameNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInitialFrameNumber(Integer value) {
        this.initialFrameNumber = value;
    }

}
