//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: [TEXT REMOVED by com.google.code.maven-replacer-plugin]
//


package de.tu_chemnitz.mi.barcd.xml.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SourceChoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SourceChoiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="device" type="{http://www.tu-chemnitz.de/informatik/mi/barcd}VideoDeviceSourceType"/>
 *         &lt;element name="video" type="{http://www.tu-chemnitz.de/informatik/mi/barcd}VideoStreamSourceType"/>
 *         &lt;element name="sequence" type="{http://www.tu-chemnitz.de/informatik/mi/barcd}ImageSequenceSourceType"/>
 *         &lt;element name="images" type="{http://www.tu-chemnitz.de/informatik/mi/barcd}ImageCollectionSourceType"/>
 *         &lt;element name="snapshot" type="{http://www.tu-chemnitz.de/informatik/mi/barcd}SnapshotSourceType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SourceChoiceType", propOrder = {
    "device",
    "video",
    "sequence",
    "images",
    "snapshot"
})
public class SourceChoiceElement {

    protected VideoDeviceSourceElement device;
    protected VideoStreamSourceElement video;
    protected ImageSequenceSourceElement sequence;
    protected ImageCollectionSourceElement images;
    protected SnapshotSourceElement snapshot;

    /**
     * Gets the value of the device property.
     * 
     * @return
     *     possible object is
     *     {@link VideoDeviceSourceElement }
     *     
     */
    public VideoDeviceSourceElement getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoDeviceSourceElement }
     *     
     */
    public void setDevice(VideoDeviceSourceElement value) {
        this.device = value;
    }

    /**
     * Gets the value of the video property.
     * 
     * @return
     *     possible object is
     *     {@link VideoStreamSourceElement }
     *     
     */
    public VideoStreamSourceElement getVideo() {
        return video;
    }

    /**
     * Sets the value of the video property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoStreamSourceElement }
     *     
     */
    public void setVideo(VideoStreamSourceElement value) {
        this.video = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link ImageSequenceSourceElement }
     *     
     */
    public ImageSequenceSourceElement getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageSequenceSourceElement }
     *     
     */
    public void setSequence(ImageSequenceSourceElement value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the images property.
     * 
     * @return
     *     possible object is
     *     {@link ImageCollectionSourceElement }
     *     
     */
    public ImageCollectionSourceElement getImages() {
        return images;
    }

    /**
     * Sets the value of the images property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageCollectionSourceElement }
     *     
     */
    public void setImages(ImageCollectionSourceElement value) {
        this.images = value;
    }

    /**
     * Gets the value of the snapshot property.
     * 
     * @return
     *     possible object is
     *     {@link SnapshotSourceElement }
     *     
     */
    public SnapshotSourceElement getSnapshot() {
        return snapshot;
    }

    /**
     * Sets the value of the snapshot property.
     * 
     * @param value
     *     allowed object is
     *     {@link SnapshotSourceElement }
     *     
     */
    public void setSnapshot(SnapshotSourceElement value) {
        this.snapshot = value;
    }

}
