//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: [TEXT REMOVED by com.google.code.maven-replacer-plugin]
//


package de.tu_chemnitz.mi.barcd.xml.binding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SourceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="device" type="{http://www.tu-chemnitz.de/informatik/mi/barcd}VideoDeviceType"/>
 *         &lt;element name="video" type="{http://www.tu-chemnitz.de/informatik/mi/barcd}ResourceType"/>
 *         &lt;element name="sequence" type="{http://www.tu-chemnitz.de/informatik/mi/barcd}ImageSequenceType"/>
 *         &lt;element name="images" type="{http://www.tu-chemnitz.de/informatik/mi/barcd}ImagesType"/>
 *         &lt;element name="snapshot" type="{http://www.tu-chemnitz.de/informatik/mi/barcd}ResourceType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SourceType", propOrder = {
    "device",
    "video",
    "sequence",
    "images",
    "snapshot"
})
public class SourceElement {

    protected VideoDeviceElement device;
    protected ResourceElement video;
    protected ImageSequenceElement sequence;
    protected ImagesElement images;
    protected ResourceElement snapshot;

    /**
     * Gets the value of the device property.
     * 
     * @return
     *     possible object is
     *     {@link VideoDeviceElement }
     *     
     */
    public VideoDeviceElement getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoDeviceElement }
     *     
     */
    public void setDevice(VideoDeviceElement value) {
        this.device = value;
    }

    /**
     * Gets the value of the video property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceElement }
     *     
     */
    public ResourceElement getVideo() {
        return video;
    }

    /**
     * Sets the value of the video property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceElement }
     *     
     */
    public void setVideo(ResourceElement value) {
        this.video = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link ImageSequenceElement }
     *     
     */
    public ImageSequenceElement getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageSequenceElement }
     *     
     */
    public void setSequence(ImageSequenceElement value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the images property.
     * 
     * @return
     *     possible object is
     *     {@link ImagesElement }
     *     
     */
    public ImagesElement getImages() {
        return images;
    }

    /**
     * Sets the value of the images property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImagesElement }
     *     
     */
    public void setImages(ImagesElement value) {
        this.images = value;
    }

    /**
     * Gets the value of the snapshot property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceElement }
     *     
     */
    public ResourceElement getSnapshot() {
        return snapshot;
    }

    /**
     * Sets the value of the snapshot property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceElement }
     *     
     */
    public void setSnapshot(ResourceElement value) {
        this.snapshot = value;
    }

}
